{
 "title": "Udacity",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status=~\"2..\"}[5m]))/sum(rate(flask_http_request_total[5m]))"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "1 - ((1 - (sum(increase(flask_http_request_total{status=\"200\"}[5m])) by(verb))/sum(increase(flask_http_request_total[5m])) by (verb))/ (1 - .80))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status=~\"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,\nsum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le, verb))"
    }
   ]
  }
 ]
}